version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        container_name: 'template_postgres'
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"

    webserver:
        build: .
        container_name: 'template_webserver'
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__CORE__FERNET_KEY="dd9+hhjzsDT8wqYlglnvhuZmY143y3r3mTvs+nspKAU=="
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/opt/airflow/dags
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

